### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [wulfeku3/project11#2]
I love the validation to make sure the link is to a valid image! There's just one issues I'd like you to fix in this project:
### Indentation

I see [some hard-tabs here](https://github.com/wulfeku3/project11/blob/master/app/models/fnaf.rb#L2-L3) and possibly also in other files. The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have _every_ file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by chrisvfritz** [comment]
Any progress here?

**Comment by wulfeku3** [comment]
How is this looking? I think I converted all of the tabs to spaces, but let me know.

**Comment by chrisvfritz** [comment]
```
Searching 80 files for "\t" (regex)

0 matches
```

:+1: :smiley:
